services:
  - type: web
    name: career-pulse
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        value: "base64:+jiyBsVifghmyDiQMy/3goQmcuJamoX+jeI6PofD5Uo="
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDb: career-pulse-db
      - key: DB_PORT
        fromDb: career-pulse-db
      - key: DB_DATABASE
        fromDb: career-pulse-db
      - key: DB_USERNAME
        fromDb: career-pulse-db
      - key: DB_PASSWORD
        fromDb: career-pulse-db